name: Exemplo de Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Verificar código
        uses: actions/checkout@v2
        
      - name: Instalar dependências
        run: |
          npm install
          
      - name: Executar teste
        run: |
          npm test
          
      - name: Ação pré-existente do GitHub
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Meu script personalizado
        run: |
          echo "Executando meu script..."
          # Adicione comandos personalizados aqui

      - name: Comando final
        run: echo "Este é o último comando a ser executado"
